name: CI

on: push

jobs:
  ci:
    name: "Lint & test"
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint-lib
      - run: npm run test-lib
