name: "NPM Publish"

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build-lib
      - name: "🚀 Publish"
        run: npm publish dist/ngx-otp-input --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
